spring:
  application.name: service
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: optional:configserver:http://localhost:8888

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/
