spring:
  application.name: auth-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: optional:configserver:http://localhost:8763

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/

server.port: 8081
