spring:
  application.name: user-service
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: fost
    password: fost
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092

server.port: 8085
